spring:
  datasource:
    url: jdbc:postgresql://postgres:puBstpH7RitaBevAgeHp@containers-us-west-154.railway.app:5878/railway 
    username: postgres
    password: puBstpH7RitaBevAgeHp
    name: spring-blog

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
